USE [Teste_tecnico]
GO

 
/****** Object:  Table [dbo].[ENDERECO_INTEGRACAO]    Script Date: 27/02/2023 16:35:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ENDERECO_INTEGRACAO]') AND type in (N'U'))
DROP TABLE [dbo].[ENDERECO_INTEGRACAO]
GO

 

/****** Object:  Table [dbo].[ENDERECO]    Script Date: 27/02/2023 16:35:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ENDERECO]') AND type in (N'U'))
DROP TABLE [dbo].[ENDERECO]
GO

 
/****** Object:  Table [dbo].[PESSOA]    Script Date: 27/02/2023 16:35:33 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PESSOA]') AND type in (N'U'))
DROP TABLE [dbo].[PESSOA]
GO



/****** Object:  Table [dbo].[PESSOA]    Script Date: 25/02/2023 21:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PESSOA](
	[IDPESSOA] [bigint] IDENTITY(1,1) NOT NULL,
	[FLNATUREZA] [int] NOT NULL,
	[DSDOCUMENTO] [varchar](20) NOT NULL,
	[NMPRIMEIRO] [varchar](100) NOT NULL,
	[NMSEGUNDO] [varchar](100) NOT NULL,
	[DTREGISTRO] [datetime] NULL,
 CONSTRAINT [PK_PESSOA] PRIMARY KEY CLUSTERED 
(
	[IDPESSOA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ENDERECO](
	[IDENDERECO] [bigint] IDENTITY(1,1) NOT NULL,
	[IDPESSOA] [bigint] NOT NULL,
	[DSCEP] [varchar](15) NULL,
 CONSTRAINT [PK_ENDERECO] PRIMARY KEY CLUSTERED 
(
	[IDENDERECO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ENDERECO]  WITH CHECK ADD  CONSTRAINT [FK_ENDERECO_PESSOA] FOREIGN KEY([IDPESSOA])
REFERENCES [dbo].[PESSOA] ([IDPESSOA])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ENDERECO] CHECK CONSTRAINT [FK_ENDERECO_PESSOA]
GO

CREATE TABLE [dbo].[ENDERECO_INTEGRACAO](
	[IDENDERECO] [bigint] NOT NULL,
	[DSUF] [varchar](50) NULL,
	[NMCIDADE] [varchar](100) NULL,
	[NMBAIRRO] [varchar](50) NULL,
	[NMLOGRADOURO] [varchar](100) NULL,
	[DSCOMPLEMENTO] [varchar](100) NULL,
 CONSTRAINT [PK_ENDERECO_INTEGRACAO] PRIMARY KEY CLUSTERED 
(
	[IDENDERECO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ENDERECO_INTEGRACAO]  WITH CHECK ADD  CONSTRAINT [ENDERECO_INTEGRACAO_FK_ENDERECO] FOREIGN KEY([IDENDERECO])
REFERENCES [dbo].[ENDERECO] ([IDENDERECO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ENDERECO_INTEGRACAO] CHECK CONSTRAINT [ENDERECO_INTEGRACAO_FK_ENDERECO]
GO
